// ── Netcracker SVE FAQ Knowledge Base ─────────────────────────
// Answers questions even when no AI API is available
// Covers: skills, roles, BSS/OSS terms, Netcracker context

export const FAQ = [
  // ── BSS/OSS Domain ──────────────────────────────────────────
  { q:['what is ocs','ocs','online charging'], a:`**OCS (Online Charging System)** is Netcracker's real-time charging engine for prepaid telecom subscribers. It makes credit reservation decisions in under 100ms per Diameter Ro/Gy request from the network. It handles millions of concurrent sessions and ensures subscribers can't be double-charged or falsely denied service. Key skills: Java, Diameter protocol, Oracle/Cassandra, real-time systems.` },
  { q:['what is bss','bss meaning','business support'], a:`**BSS (Business Support Systems)** covers the customer-facing and business operations side of telecom software — billing, CRM, order management, product catalog, and revenue management. At Netcracker, BSS products include CBM (billing), OCS (online charging), CRM, and POC (Product Offering Catalog). BSS is one of Netcracker's core product lines deployed at Tier 1 operators globally.` },
  { q:['what is oss','oss meaning','operations support'], a:`**OSS (Operations Support Systems)** covers the network-facing side — network inventory, fault management, provisioning, and service fulfillment. At Netcracker, OSS products manage the network resources that BSS products sell to customers. OSS and BSS together form the complete telecom software stack.` },
  { q:['what is mediation','mediation system','active mediation'], a:`**Mediation** at Netcracker (Active Mediation) collects and normalises usage data — CDRs, xDRs, and network events — from network elements and routes them to billing and analytics systems. It handles billions of records daily at Tier 1 operators, doing format conversion, duplicate detection, and threshold-based routing. Core skills: Java, Kafka, Oracle, high-throughput data processing.` },
  { q:['what is cbm','customer billing','billing management'], a:`**CBM (Customer Billing Management)** is Netcracker's billing engine — it rates usage records, applies tariff rules, generates invoices, and manages the financial lifecycle for telecom subscribers. It handles complex scenarios: multi-currency billing across 40+ countries, retroactive re-rating when tariffs change, and legally compliant invoice generation. Core skills: Java, Oracle/PostgreSQL, PL/SQL, billing domain knowledge.` },
  { q:['what is crm','customer relationship'], a:`**CRM (Customer Relationship Management)** at Netcracker manages subscriber lifecycle — account creation, service ordering, complaints, and agent interactions. It integrates with the Product Offering Catalog for configurable offers and connects with order management for service fulfillment. Skills needed: Java, Spring Boot, REST APIs, telecom domain knowledge.` },
  { q:['what is poc','product catalog','product offering'], a:`**POC (Product Offering Catalog)** is Netcracker's central repository of telecom products, bundles, prices, and eligibility rules. It drives what can be sold, how it's priced, and what can be combined. Managing 50,000+ product variants with overlapping eligibility rules at Tier 1 operators is the core engineering challenge. Skills: Java, Oracle/MongoDB, complex data modelling.` },
  { q:['what is nrm','network resource','resource management'], a:`**NRM (Network Resource Management)** at Netcracker manages physical and logical network inventory — nodes, links, services, and the relationships between them. It's the OSS component that tracks what network resources exist and which are allocated to customers. Core skills: Java, Oracle, network topology data modelling, OSS domain expertise.` },
  { q:['what is cdr','call detail record'], a:`**CDR (Call Detail Record)** is a data record produced by telecom network elements documenting every call, SMS, or data session — duration, endpoints, volume, timestamps. CDRs flow through mediation into billing for rating and charging. Handling billions of CDRs daily with zero loss is a core Netcracker engineering challenge.` },
  { q:['what is diameter','diameter protocol'], a:`**Diameter** is the IETF authentication, authorization, and accounting (AAA) protocol used in 4G/5G networks for real-time charging (Ro/Gy interfaces to OCS), policy control (Gx to PCRF), and subscriber authentication. It replaced RADIUS for telecom applications. Critical skill for OCS and NRM engineers at Netcracker.` },
  { q:['what is ia analysis','ia analysis'], a:`**IA Analysis** at Netcracker refers to Impact Analysis — the process of assessing how a change, bug fix, or new feature affects other parts of the BSS/OSS system. It's a key skill for Business Analysts and Solution Architects working on complex multi-module telecom platforms where a single change can cascade across billing, mediation, and provisioning.` },

  // ── Technology Skills ────────────────────────────────────────
  { q:['what is kafka','apache kafka','kafka skills'], a:`**Apache Kafka** is Netcracker's backbone for real-time event streaming — carrying CDR streams from mediation to billing, propagating order state changes across microservices, and enabling async integration between OCS and CBM. Senior engineers design topic partitioning strategies for millions of CDRs/hour and implement exactly-once semantics for financial data. Kafka is one of the most in-demand skills at Netcracker.` },
  { q:['what is kubernetes','k8s','kubernetes skills'], a:`**Kubernetes** is the container orchestration platform for all Netcracker cloud-native BSS/OSS deployments. Engineers design HPA policies for CDR processing load, StatefulSets for Oracle RAC/Cassandra, and Istio service mesh for PCI-compliant billing flows. It's critical for cloud-native product deployments on AWS EKS, Azure AKS, and customer-managed clusters.` },
  { q:['what is java','java skills','java developer'], a:`**Java** is the primary language of Netcracker's BSS/OSS platform — billing engine, order management, mediation, and integration adapters are all Java 11/17. Senior engineers tune JVM heap for billing batch jobs (GC pause budgets under 200ms), profile with JFR for CDR throughput bottlenecks, and design thread-safe concurrent processing for parallel order execution.` },
  { q:['what is python','python skills'], a:`**Python** at Netcracker is used for automation, monitoring scripts, SVT tooling, and data pipeline development. SVT teams use pytest frameworks for E2E verification, SDSI monitoring teams write Ansible playbooks and Prometheus exporters, and R&D uses it for ML prototyping. Most widely used in the Testing and SDSI BUs.` },
  { q:['what is docker','docker skills'], a:`**Docker** provides the container packaging standard for Netcracker's CI/CD pipeline. Every product component ships as a multi-stage Docker image built in Jenkins, pushed to a private registry, and deployed via Helm. Critical skill for all cloud deployment roles across SDSI, SE, and SDNC BUs.` },
  { q:['what is ansible','ansible skills'], a:`**Ansible** is Netcracker's primary deployment automation tool for on-premise operator environments — provisioning VMs, configuring middleware (WebLogic, JBoss), deploying product packages, and running health checks. Writing idempotent playbooks for 200+ host environments is the key senior skill. Primarily used in SDSI and IT BUs.` },
  { q:['what is microservice','microservices architecture'], a:`**Microservices** at Netcracker is the architectural pattern for cloud-native BSS/OSS products — each product capability (billing, OCS, CRM) decomposed into independently deployable services with REST/Kafka communication. Senior architects design service boundaries, shared library strategies, and inter-service resilience patterns using Resilience4j circuit breakers.` },

  // ── Roles & Functions ────────────────────────────────────────
  { q:['billing analyst','billing analyst skills','billing analyst role'], a:`A **Billing Analyst** at Netcracker works on CBM/RBM implementation and configuration — understanding customer tariff requirements, mapping billing rules to the platform, and validating output. Key skills needed: SQL/Oracle, billing domain knowledge (CBM, RBM, OCS), Java basics, PL/SQL for data migration, and strong analytical ability. Most Billing Analyst roles are in the SE and SDNC BUs.` },
  { q:['business analyst','ba role','ba skills'], a:`**Business Analysts (BA)** at Netcracker bridge customer requirements and technical delivery — writing functional specs, running workshops, and validating solutions. Key skills: domain knowledge (BSS/OSS), requirements documentation, API specifications, UML/Visio for process diagrams. BA specialisations include CBM BA, CRM BA, POC BA, and OCS BA — each focused on one product area.` },
  { q:['solution architect','sa role','architect skills'], a:`**Solution Architects** at Netcracker design end-to-end BSS/OSS solutions for Tier 1 operators — defining integration points, data models, deployment topology, and migration strategies. They need deep domain knowledge (5+ years BSS/OSS), strong technical skills (Java, microservices, cloud), and customer-facing communication skills. Most SA roles are in the SE and SDNC BUs.` },
  { q:['devops engineer','devops role','devops skills'], a:`**DevOps Engineers** at Netcracker own the end-to-end delivery pipeline for a product deployed at 20+ operator environments globally — Jenkins/GitLab pipelines, Helm chart packaging, Ansible provisioning, and release management. Critical skills: Kubernetes, Docker, Ansible, Jenkins, Terraform. Air-gapped deployment experience (no internet access) is a key differentiator for senior roles.` },
  { q:['test engineer','qa engineer','testing skills','svt'], a:`**SVT (System Verification & Testing)** engineers at Netcracker verify end-to-end product quality — writing test plans, executing regression suites, and automating test cases. Key skills: Java/Python for automation, Selenium/Playwright for UI testing, SQL for data validation, and BSS/OSS domain knowledge to understand what to test. The Testing BU specialises in this.` },

  // ── BUs at Netcracker ────────────────────────────────────────
  { q:['what is se bu','se business unit','software engineering bu'], a:`**SE (Software Engineering)** is Netcracker's largest BU with 18 functions — responsible for core product development of BSS/OSS modules. SE engineers build the billing engine, OCS, mediation, and integration framework. Skills span Java, Oracle, Kafka, Kubernetes, Spring Boot, and telecom domain expertise.` },
  { q:['what is sdsi','sdsi bu','service delivery'], a:`**SDSI (Service Delivery & Support Infrastructure)** handles cloud deployments, monitoring, and managed services for operator customers. SDSI teams deploy Netcracker products on AWS/Azure/on-premise, manage SLAs, and handle production incidents. Skills: Kubernetes, Ansible, Prometheus/Grafana, cloud (AWS/Azure), scripting (Python/Bash).` },
  { q:['what is sdnc','sdnc bu'], a:`**SDNC (Solution Design & NC)** covers solution architecture and business analysis for customer engagements — designing how Netcracker products meet operator requirements. SDNC roles include BA (Business Analyst), Solution Architect, and POC specialists. Skills: BSS/OSS domain expertise, API specs, requirements documentation, Java basics.` },
  { q:['what is svt bu','svt testing'], a:`**SVT (System Verification & Testing)** BU is responsible for end-to-end product quality assurance. SVT engineers write and execute test plans, build automation frameworks, and verify that BSS/OSS products meet functional and performance requirements. Skills: Java/Python testing frameworks, Selenium, SQL, CI/CD for test pipelines.` },
  { q:['what is it bu','it department'], a:`**IT** at Netcracker manages internal infrastructure — cloud support, security, application management, and DevOps tooling for Netcracker's own systems (not customer deployments). The IT BU has 12 functions covering cloud, security (CISA, EDR, SIEM), DevOps, and IT application management.` },

  // ── General Questions ────────────────────────────────────────
  { q:['what is netcracker','about netcracker'], a:`**Netcracker Technology** is a global BSS/OSS software company (subsidiary of NEC) that builds billing, ordering, mediation, and network management products for Tier 1 telecom operators like Verizon, NTT, Etisalat, and SingTel. Headquartered in Waltham, MA with major engineering centres in Bangalore, Hyderabad, Pune, and globally. The Skill Visibility Engine tracks skills across Netcracker's engineering BUs.` },
  { q:['how to search','how to use','what can i search'], a:`You can search for: **Skills** (Java, Kafka, Kubernetes, OCS, Mediation), **Roles** (Billing Analyst, DevOps Engineer, BA), **BSS/OSS terms** (CDR, Diameter, POC, NRM), or **BUs** (SE, SDSI, SDNC). Each search shows matching skills from our database, glossary definitions, and related JDs. Click any skill to see which BUs and leaders have it.` },
  { q:['who knows kafka','who has kafka','kafka in which bu'], a:`**Kafka** is used across multiple Netcracker BUs. Search "Kafka" in the Skill Matrix to see the exact functions and leaders. It's most common in SE (backend microservices), SDSI (cloud monitoring pipelines), and SDNC (integration design). Click the Kafka skill chip to see all BUs, functions, and leaders with this skill.` },
  { q:['who knows kubernetes','kubernetes in which bu'], a:`**Kubernetes** is a core skill across SE, SDSI, SDNC, and IT BUs. Use the Skill Matrix search to find all functions. SDSI uses it for production deployments, SE for cloud-native development, and SDNC for solution design. Click any Kubernetes result to see the full BU coverage breakdown.` },
];

export function searchFAQ(query) {
  const q = query.toLowerCase().trim();
  const matches = FAQ.filter(f =>
    f.q.some(keyword => {
      // exact match or contains
      if (q.includes(keyword) || keyword.includes(q)) return true;
      // word overlap — at least 2 words in common
      const qWords = q.split(/\s+/).filter(w=>w.length>2);
      const kWords = keyword.split(/\s+/).filter(w=>w.length>2);
      return qWords.some(w => kWords.includes(w));
    })
  );
  return matches[0]?.a || null;
}
